Return correct status codes in arrivals backend when handling EIS router responses
hmrc/transits-movements-trader-at-departure pull request #52
Opened 2020-10-31 09:30 UTC by marcinkrykowski

Based on: https://github.com/hmrc/transit-movements-trader-at-destination/pull/154 and https://jira.tools.tax.service.gov.uk/browse/CTDA-803. Needs to wait till John is back.

2020-11-03 09:12 UTC, crystalmark requested changes

2020-11-03 09:12 UTC, crystalmark commented on app/controllers/DeparturesController.scala
> +                        Status(submissionResult.httpStatus)(submissionResult.asString)
Could you add some tests that would cover this case please?

2020-12-24 15:32 UTC, jhkldev commented
test this please

2020-12-24 15:37 UTC, jhkldev commented
test this please

2020-12-24 17:00 UTC, jhkldev commented
test this please

2020-12-29 11:48 UTC, amaalali approved these changes

2020-12-29 12:10 UTC, RobertLaverick requested changes
@jhkldev can you please make sure there are tickets to address using the new update endpoint more broadly, even if it is simply a spike ticket so that the declaration of "depreciated" repository endpoints isn't left by the wayside.

Also, whilst I appreciate the technical value of the change, and I'll let it be merged in, I'd like you to highlight that the spike should obfuscate the database-level considerations from the rest of the system - something that would typically be called DepartureService (we might need to rename our current DepartureService to reclaim that name in the spike - perhaps to ModelBuilder?). Can you please create this ticket and add it to the PR in a reply comment, and then I'll approve.

2020-12-29 13:00 UTC, jhkldev commented
> @jhkldev can you please make sure there are tickets to address using the new update endpoint more broadly, even if it is simply a spike ticket so that the declaration of "depreciated" repository endpoints isn't left by the wayside.
> 
> Also, whilst I appreciate the technical value of the change, and I'll let it be merged in, I'd like you to highlight that the spike should obfuscate the database-level considerations from the rest of the system - something that would typically be called DepartureService (we might need to rename our current DepartureService to reclaim that name in the spike - perhaps to ModelBuilder?). Can you please create this ticket and add it to the PR in a reply comment, and then I'll approve.

https://jira.tools.tax.service.gov.uk/browse/CTDA-1025

2020-12-29 13:23 UTC, RobertLaverick approved these changes

2020-12-29 13:28 UTC, merged