divided JsonHelper into translating and nontranslating versions to st…
hmrc/transits-movements-trader-at-departure pull request #86
Opened 2021-03-31 12:05 UTC by RobertLaverick

…ore untranslatedMessageJson in db

2021-03-31 14:08 UTC, amaalali requested changes
We should stick to the same architecture as in Arrivals, see [here](https://github.com/hmrc/transit-movements-trader-at-destination/blob/master/app/models/MovementMessage.scala#L40-L48).

We don't want or need to call `JsonHelper` anywhere  other than in `app/models/Message.scala`

2021-03-31 14:08 UTC, amaalali commented on it/api/PDFRetrievalControllerISpec.scala
> +          List(MessageWithoutStatus(LocalDateTime.now(), MessageType.ReleaseForTransit, <released></released>, 2, convertXmlToJson(<released></released>.toString)))
This can be dummy json here

2021-03-31 14:08 UTC, amaalali commented on it/api/PDFRetrievalControllerISpec.scala
> +          MessageWithStatus(LocalDateTime.now(), MessageType.DepartureDeclaration, <departure></departure>, MessageStatus.SubmissionSucceeded, 1, convertXmlToJson(<departure></departure>.toString)),
We don't need to translate this

2021-03-31 14:11 UTC, RobertLaverick commented on app/models/Message.scala
> +        (__ \ "messageJson").read[JsObject].orElse(Reads.pure(Json.obj()))
Last time I checked departures backend IS live and used by the front-end. You've confused me here.

2021-04-06 08:05 UTC, amaalali commented on app/models/Message.scala
> +        (__ \ "messageJson").read[JsObject].orElse(Reads.pure(Json.obj()))
Departures FE is not live but as discussed, this is for pre-prod environments where there is live data that we want to gracefully handle

2021-04-06 08:05 UTC, amaalali commented on app/models/Message.scala
> +        (__ \ "messageJson").read[JsObject].orElse(Reads.pure(Json.obj()))
Same as above

2021-04-07 14:56 UTC, amaalali approved these changes
I think that we can improve the code by encapsulating all XML to Json conversion in `MovementMessage` similar to what is done in Arrivals (see https://github.com/hmrc/transit-movements-trader-at-destination/blob/master/app/audit/AuditService.scala) but this is functionally correct for the current purposes. We should ideally deal with this technical debt now if possible but it can be followed up in another PR

2021-04-09 09:26 UTC, amaalali approved these changes

2021-04-09 13:41 UTC, crystalmark approved these changes

2021-04-13 09:22 UTC, merged